# Generated by Django 3.0.5 on 2020-04-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_upload_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-upload_date']},
        ),
    ]
